[package]
name = "rusthook"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
tokio = { version = "1.39.3", features = ["rt-multi-thread", "macros", "sync" ]}
futures = { version = "0.3.30" }
log = { version = "0.4.17" }
env_logger = { version = "0.11.5" }
serde = { version = "1.0.209", features = ["derive"]}   
serde_json = { version = "1.0.127" }
base64 = "0.22.1"
ed25519 = "2.2.3"
ed25519-dalek = "2.1.1"
reqwest = { version = "0.12.7", features = ["json"] }
poem = "3.0.4"
async-trait = "0.1.81"
