edition="2021"
max_width = 120
reorder_imports = true
brace_style = "SameLineWhere"
blank_lines_upper_bound = 1
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = false
use_field_init_shorthand = true
unstable_features = true
format_strings = true
